graph TD; A(root) --> B(src); B --> C(main.ts); B --> D(app.module.ts); B --> E(app.controller.ts); B --> F(app.service.ts); B --> G(config); G --> G1(configuration.ts); B --> H(common); H --> H1(guards); H1 --> H1a(auth.guard.ts); H --> H2(interceptors); H2 --> H2a(logging.interceptor.ts); H --> H3(pipes); H3 --> H3a(validation.pipe.ts); B --> I(modules); I --> I1(users); I1 --> I1a(users.module.ts); I1 --> I1b(users.controller.ts); I1 --> I1c(users.service.ts); I --> I2(auth); I2 --> I2a(auth.module.ts); I2 --> I2b(auth.service.ts); I2 --> I2c(auth.controller.ts); I2 --> I2d(jwt.strategy.ts;)